### ISSUE TITLE
Choose Best Weather API

### ISSUE THREAD

**Issue by AllendeTruth** [chingu-voyage5/Geckos-Team-15#3]

**Comment by AllendeTruth** [comment]
I've used "open weather map" api before. It works fairly well. Open to any other suggestions

**Comment by nroode** [comment]
That works... there's a set of icons I've used previously that integrate with it nicely.  Will have to find those again.

**Comment by AllendeTruth** [comment]
Sounds good! When I was choosing weather APIs I remember dark ski api had some nice animated icons that go with it as well.

**Comment by TyreKing** [comment]
I checked out the api's you guys mentioned, they look simple enough, and i think it looks good.
